# Generated by Django 4.0.5 on 2022-07-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sell_shares',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_shares',
        ),
    ]
