# Generated by Django 4.0.5 on 2022-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
