# Generated by Django 4.0.5 on 2022-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_category_project_shares_alter_business_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mandatory_filling',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
    ]
