# Generated by Django 4.0.5 on 2022-07-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_shares_percentage_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='sell_equity',
            field=models.IntegerField(default=0),
        ),
    ]
