# Generated by Django 4.0.5 on 2022-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_project_total_price_alter_project_total_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sell_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
