# Generated by Django 4.0.5 on 2022-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_mandatory_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mandatory_filling',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')]),
        ),
    ]
