# Generated by Django 4.0.5 on 2022-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_mandatory_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='mandatory_filling',
            field=models.CharField(max_length=20, verbose_name=(('True', 'Yes'), ('False', 'No'))),
        ),
    ]
