# Generated by Django 4.0.5 on 2022-07-03 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_shares_percentage_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cro',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
