# Generated by Django 4.0.5 on 2022-07-01 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_mandatory_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='mandatory_filling',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=20),
        ),
    ]
