# Generated by Django 4.0.5 on 2022-07-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_project_investor_percentage_equity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyflow',
            name='project_investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moneyflow', to='business.project_investor'),
        ),
    ]
