# Generated by Django 3.2 on 2022-07-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_project_investor_percentage_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_investor',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvestorShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('percentage_equity', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.project_investor')),
            ],
        ),
    ]
