# Generated by Django 3.2 on 2022-07-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20220703_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_project', to='business.project'),
        ),
    ]
